### PR TITLE
Revert "readme file edit"

### PR DESCRIPTION
**Pull request by Siddharthgolecha**
Reverts dscmbm/StudyPods-v2.0#53

@Satwikan Please review the files properly without merging them into the main branch, here the readme file of the main project itself was changed.

### CODE REVIEW

**Comment by Satwikan** [comment]
It reverts that commit @Siddharthgolecha but still its not our original readme fole

**Comment by Satwikan** [comment]
please revert this commit 165ec83944aba0ab73b4a8c690fed03f41a82c68 this is what changed our readme file to begin with @Siddharthgolecha

**Comment by Siddharthgolecha** [comment]
@Satwikan Actually we need to revert twice

**Comment by Siddharthgolecha** [comment]
@Satwikan Actually we need to revert twice

**Pull request merged**
